### PR TITLE
Add support for specifying a minimum protocol version

### PR DESCRIPTION
**Pull request by conradoplg**
For https://github.com/ZcashFoundation/dnsseeder/issues/10 but instead of changing the constant, allow the caller to specify the version. (The constant will be then specified by `dnsseeder` in another PR)

### CODE REVIEW

**Review by teor2345 — APPROVED** [review]
Looks good!

We'd usually upgrade to the latest upstream version before making changes like this. But this change is urgent.

I don't think the risk or time for the upgrade is worth it, if we want to replace this seeder anyway. We'd need a decent test suite and health check to handle those risks, and we don't have them.

**Review by teor2345 — CHANGES_REQUESTED** [review]
Actually, I'd like us to consider using a per-network minimum protocol version, because it provides more reliable peers from the seeder.

What do you think?

For details see:
https://github.com/ZcashFoundation/dnsseeder/pull/18#discussion_r889758831

**Review by teor2345 — APPROVED** [review]
Looks like we did versions for each network elsewhere.

**Comment by conradoplg** [comment]
> Looks like we did versions for each network elsewhere.

Done in https://github.com/ZcashFoundation/dnsseeder/pull/18

**Pull request merged**
